apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:    
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      volumes:
        - name: scan8-common
          persistentVolumeClaim:
            claimName: scan8pvc1
      containers:
      - name: worker
        image: scan8-worker
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        stdin: true
        tty: true
        volumeMounts:
          - mountPath: "/app/common/"
            name: scan8-common

