apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave
spec:
  replicas: 3
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
    spec:
      containers:
      - name: slave
        image: alpine:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-ec", "sleep 1000"]
        
